DROP TABLE IF EXISTS typo;

CREATE TABLE IF NOT EXISTS typo (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	slug TEXT UNIQUE NOT NULL,
	label TEXT,
	body TEXT,
	heading TEXT,
	subheading TEXT,
	keywords TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO typo (slug, label, heading, subheading, body, keywords) VALUES
	('artistic-handcrafted', 'Artistic and Handcrafted', "'Poiret One', cursive", "'Indie Flower', cursive", "'Dancing Script', cursive", 'artistic, handcrafted'),
	('bold-playful', 'Bold and Playful', "'Fredoka One', sans-serif", "'Oswald', sans-serif", "'Nunito', sans-serif", 'bold, playful'),
	('corporate', 'Corporate', "'Lato', sans-serif", "'Open Sans', sans-serif", "'Roboto', sans-serif", 'corporate'),
	('elegant-script', 'Elegant Script', "'Great Vibes', cursive", "'Sacramento', cursive", "'Quicksand', sans-serif", 'elegant, script'),
	('elegant-sophisticated', 'Elegant and Sophisticated', "'Cormorant', serif", "'Crimson Text', serif", "'Source Sans Pro', sans-serif", 'elegant, sophisticated'),
	('fun-playful', 'Fun and Playful', "'Baloo', cursive", "'Bangers', cursive", "'Lato', sans-serif", 'fun, playful'),
	('futuristic-clean', 'Futuristic and Clean', "'Poppins', sans-serif", "'Roboto Condensed', sans-serif", "'Nunito Sans', sans-serif", 'futuristic, clean'),
	('geometric-sans-serif', 'Geometric Sans-Serif', "'Roboto Condensed', sans-serif", "'Ubuntu', sans-serif", "'Noto Sans', sans-serif", 'geometric, sans-serif'),
	('handwritten', 'Handwritten', "'Pacifico', sans-serif", "'Amatic SC', cursive", "'Indie Flower', cursive", 'handwritten'),
	('luxury-elegance', 'Luxury and Elegance', "'Cormorant Garamond', serif", "'Parisienne', cursive", "'Lato', sans-serif", 'luxury, elegance'),
	('minimalist', 'Minimalist', "'Source Sans Pro', sans-serif", "'Lato', sans-serif", "'Poppins', sans-serif", 'minimalist'),
	('modern-serif', 'Modern Sans-Serif', "'Montserrat', sans-serif", "'Raleway', sans-serif", "'Open Sans', sans-serif", 'modern, sans-serif'),
	('nature-organic', 'Nature and Organic', "'Caveat', cursive", "'Satisfy', cursive", "'Dosis', sans-serif", 'nature, organic'),
	('playful-casual', 'Playful and Casual', "'Luckiest Guy', cursive", "'Pacifico', cursive", "'Nunito Sans', sans-serif", 'playful, casual'),
	('professional-business', 'Professional and Business', "'Raleway', sans-serif", "'Montserrat', sans-serif", "'Roboto', sans-serif", 'professional, business'),
	('retro', 'Retro', "'Lobster', cursive", "'Pacifico', cursive", "'Indie Flower', cursive", 'retro'),
	('serif-elegance', 'Serif Elegance', "'Crimson Text', serif", "'Merriweather', serif", "'Source Sans Pro', sans-serif", 'serif, elegance'),
	('tech-modern', 'Tech and Modern', "'Exo 2', sans-serif", "'Orbitron', sans-serif", "'Raleway', sans-serif", 'tech, modern'),
	('vintage-rustic', 'Vintage and Rustic', "'Abril Fatface', cursive", "'Josefin Slab', serif", "'Lora', serif", 'vintage, rustic'),
	('psychedelic-pop', 'Psychedelic Pop', "'Rubik Glitch', cursive", "'Permanent Marker', cursive", "'Comfortaa', sans-serif", 'psychedelic, pop');
INSERT INTO typo (slug, label, heading, subheading, body, keywords) VALUES
	('elegant-refined', 'Elegant and Refined', "'Playfair Display', serif", "'Cinzel Decorative', serif", "'Lora', serif", 'elegant, refined, nouveau'),
	('retro-funky', 'Retro and Funky', "'Monoton', cursive", "'Pacifico', cursive", "'Quicksand', cursive", 'retro, funky, nouveau'),
	('modern-minimalist', 'Modern and Minimalist', "'Raleway', sans-serif", "'Montserrat', sans-serif", "'Open Sans', sans-serif", 'modern, minimalist, nouveau'),
	('vintage-script', 'Vintage Script', "'Great Vibes', cursive", "'Sacramento', cursive", "'Merriweather', serif", 'vintage, script, nouveau'),
	('futuristic-tech', 'Futuristic and Tech', "'Orbitron', sans-serif", "'Audiowide', sans-serif", "'Roboto', sans-serif", 'futuristic, tech, nouveau'),
	('romantic-soft', 'Romantic and Soft', "'Parisienne', cursive", "'Amatic SC', cursive", "'Josefin Sans', sans-serif", 'romantic, soft, nouveau'),
	('playful-childlike', 'Playful and Childlike', "'Chewy', cursive", "'Baloo 2', cursive", "'Nunito', sans-serif", 'playful, childlike, nouveau'),
	('horror-mysterious', 'Horror and Mysterious', "'Creepster', cursive", "'Nosifer', cursive", "'Alegreya', serif", 'horror, mysterious, nouveau'),
	('bold-impactful', 'Bold and Impactful', "'Bebas Neue', sans-serif", "'Oswald', sans-serif", "'Roboto Condensed', sans-serif", 'bold, impactful, nouveau'),
	('classic-newspaper', 'Classic Newspaper', "'IM Fell English SC', serif", "'Vollkorn SC', serif", "'Merriweather', serif", 'classic, newspaper, nouveau'),
	('street-art', 'Street Art', "'Fredericka the Great', cursive", "'Rock Salt', cursive", "'PT Sans', sans-serif", 'street, art, nouveau'),
	('sci-fi-minimal', 'Sci-Fi Minimal', "'Exo 2', sans-serif", "'Titillium Web', sans-serif", "'Source Code Pro', sans-serif", 'sci-fi, minimal, nouveau'),
	('handwritten-notes', 'Handwritten Notes', "'Kalam', cursive", "'Patrick Hand', cursive", "'Open Sans', sans-serif", 'handwritten, notes, nouveau'),
	('luxury-brand', 'Luxury Brand', "'Cormorant Garamond', serif", "'Playfair Display SC', serif", "'Lato', sans-serif", 'luxury, brand, nouveau'),
	('comic-book', 'Comic Book', "'Bangers', cursive", "'Luckiest Guy', cursive", "'Cabin', sans-serif", 'comic, book, nouveau'),
	('old-west', 'Old West', "'Rye', cursive", "'Special Elite', cursive", "'Roboto Slab', serif", 'old, west, nouveau'),
	('minimal-serif', 'Minimal Serif', "'DM Serif Display', serif", "'Prata', serif", "'Spectral', serif", 'minimal, serif, nouveau'),
	('futuristic-neon', 'Futuristic Neon', "'Press Start 2P', cursive", "'Orbitron', cursive", "'Share Tech Mono', cursive", 'futuristic, neon, nouveau');


INSERT INTO typo (slug, label, heading, subheading, body, keywords) VALUES
	('carnival-circus', 'Carnival Circus', "'Ewert', cursive", "'Butcherman', cursive", "'Concert One', sans-serif", 'carnival, circus, eccentric'),
	('punk-rock', 'Punk Rock', "'Black Ops One', cursive", "'Rock Salt', cursive", "'Anton', sans-serif", 'punk, rock, eccentric'),
	('retro-futurism', 'Retro Futurism', "'Audiowide', cursive", "'Russo One', cursive", "'Exo', sans-serif", 'retro, futurism, eccentric'),
	('candy-shop', 'Candy Shop', "'Cherry Cream Soda', cursive", "'Cookie', cursive", "'Comfortaa', sans-serif", 'candy, shop, eccentric'),
	('freak-show', 'Freak Show', "'Butcherman', cursive", "'Ewert', cursive", "'Sigmar One', sans-serif", 'freak, show, eccentric'),
	('wild-west-wanted', 'Wild West Wanted', "'Rye', cursive", "'Smokum', cursive", "'Roboto Slab', sans-serif", 'wild, west, wanted, eccentric'),
	('surreal-dream', 'Surreal Dream', "'Sofia', cursive", "'Marck Script', cursive", "'Quicksand', sans-serif", 'surreal, dream, eccentric'),
	('steampunk', 'SteamPunk', "'Metamorphous', cursive", "'Almendra SC', cursive", "'Spectral SC', sans-serif", 'steampunk, eccentric'),
	('funky-disco', 'Funky Disco', "'Slackey', cursive", "'Bubblegum Sans', cursive", "'Cabin Sketch', sans-serif", 'funky, disco, eccentric'),
	('haunted-carnival', 'Haunted Carnival', "'Eater', cursive", "'Rye', cursive", "'Special Elite', sans-serif", 'haunted, carnival, eccentric'),
	('wavy-groovy', 'Wavy Groovy', "'Faster One', cursive", "'Righteous', cursive", "'Maven Pro', sans-serif", 'wavy, groovy, eccentric'),
	('fantasy-fairy-tale', 'Fantasy Fairy Tale', "'Uncial Antiqua', cursive", "'MedievalSharp', cursive", "'EB Garamond', sans-serif", 'fantasy, fairy, tale, eccentric'),
	('alien-transmission', 'Alien Transmission', "'Codystar', cursive", "'Orbitron', cursive", "'Saira Semi Condensed', sans-serif", 'alien, transmission, eccentric'),
	('comic-explosion', 'Comic Explosion', "'Bangers', cursive", "'Freckle Face', cursive", "'Acme', sans-serif", 'comic, explosion, eccentric'),
	('glitch-cyberpunk', 'Glitch Cyberpunk', "'Rubik Pixels', cursive", "'Jersey 25', cursive", "'Share Tech Mono', sans-serif", 'glitch, cyberpunk, eccentric'),
	('retro-diner', 'Retro Diner', "'Monoton', cursive", "'Lobster', cursive", "'Signika', sans-serif", 'retro, diner, eccentric'),
	('pixel-arcade', 'Pixel Arcade', "'Press Start 2P', cursive", "'Silkscreen', cursive", "'VT323', sans-serif", 'pixel, arcade, eccentric'),
	('spooky-playful', 'Spooky Playful', "'Nosifer', cursive", "'Creepster', cursive", "'Baloo 2', sans-serif", 'spooky, playful, eccentric'),
	('graffiti-urban', 'Graffiti Urban', "'Wallpoet', cursive", "'Rock Salt', cursive", "'Changa', sans-serif", 'graffiti, urban, eccentric');
